name: Deploy customer frontend as a webapp

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: "11.x"

      - name: setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.5"

      - name: inject environment
        shell: bash
        run: |
          echo TODO: inject env file

      - name: build flutter web
        run: |
          flutter packages pub get;
          flutter packages pub run build_runner build;
          flutter build web --release --web-renderer canvaskit

      - name: Login
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: aws s3 sync ./build/web s3://app.ynra.eu
